language: go
go:
  - 1.9

before_deploy:
  - go get -u github.com/laher/goxc
  - mkdir -p $TRAVIS_BUILD_DIR/dist
  - goxc -d=$TRAVIS_BUILD_DIR/dist -bc=darwin -tasks=clean-destination,xc,archive,rmbin

deploy:
  provider: releases
  api_key:
    secure: KTNCddxzbrry6rWId0Gq91vWuOKDz/TCjqfiCdD5xdLgKbbPTrhaf6CwwCRgjist2PNizLc8O+s/0qpYcAy54+xM28jnslsK+z/LSHcMqzWrg8TZbMCmYZZLcws15mWGhghgtEA5Cy+4DrcAXpMgARvgOtvIdhsnGSV3Cg9RfKoSnPRgP8TzxQP/JzmtaKqCElp+mdiBtaUSWJl+vTdWn76YuYVXzwebcGchTbqOivUtjhqyaabbxmow+X3zFEFaFeKrZDP4aHh8Fa5ge55GlzlpuaYAD/IIl0e79bk3QOm6HmnI6TRAk0CufoqqMvtXnw9xvCpCJIPFwVE5fqWgQkDYLj3kz1s5jMta/U5W9cMJm3AVqihOfgt3Sx3EhKeehcMwdcrr8+aZRXQW7vR7m/ZDL768xft2xVpo0lzjcelSiM3vXxPIxxl9hyySwLR0qUmW+3aBwZnw99R/zgyuBwbyxo0kI+5B5pFJkxkboyfYw2zTWlrhXsWGpTbYOP9izG1CsB7kyIH5OMVpderTIk2XA8b9s+QZJrbDcMMoqiR3W2yIQ3exJpX6XzTm96tbLdDxy8SsKI/NRXqkHr3zQ4++5RMyuG2h/e050bocA6fmlgmluBWJhuq2hKNQldy4HSnx9fdg9vTJfgOIWSSZqitiFh6fCWm01HN7TjYQpb8=
  file_glob: true
  file: "$TRAVIS_BUILD_DIR/dist/**/*.{tar.gz,zip}"
  on:
    tags: true
    repo: polidog/slack-wifi-status
    condition: "$TRAVIS_TAG =~ ^v[0-9].*$"
